version: '2'

services:
  web:
    image: odoo:12.0
    container_name: odoo
    depends_on:
      - db
    networks:
      - odoo_lan
      - wan
    volumes:
      - odoo-web-data:/var/lib/odoo
        #- ./config:/etc/odoo
        #- ./addons:/mnt/extra-addons
    labels:
      - "traefik.enable=true"
      - "traefik.frontend=Host:odoo.museebolo.ch"
      - "traefik.port=8069"
      - "traefik.docker.network=wan"
  db:
    image: postgres:10
    container_name: odoodb
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  odoo_lan:
    driver: bridge
  wan:
    external: true


# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
