version: '3.7'

services:
  web:
    image: odoo:11.0
    depends_on:
      - db
    restart: always
    networks:
      - lan
    ports:
      - "80:8069"
    volumes:
      - web-data:/var/lib/odoo
      - ./backup/odoo11/addons:/mnt/extra-addons
      #- ./config:/etc/odoo
    environment:
      #- HOST=db
      #- PORT=5432
      - USER=<USER>
      - PASSWORD=<PASSWORD>
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

  db:
    image: postgres:12.2-alpine
    restart: always
    networks:
      - lan
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=<USER>
      - POSTGRES_PASSWORD=<PASSWORD>
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

volumes:
  web-data:
  db-data:
  extra-addons:

networks:
  lan:
    driver: bridge


# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
