version: '3.7'

services:
  web:
    image: odoo:11.0
    depends_on:
      - db
    restart: always
    networks:
      - lan
      - wan
    volumes:
      - web-data:/var/lib/odoo
      - extra-addons:/mnt/extra-addons
      #- ./config:/etc/odoo
    environment:
      #- HOST=db
      #- PORT=5432
      - USER=Oj8Du8
      - PASSWORD=koo4hah1Lus6bazo
    labels:
      - traefik.enable=true
      - traefik.http.routers.http-odoo-museebolo-ch.rule=Host(`odoo.museebolo.ch`)
      - traefik.http.routers.http-odoo-museebolo-ch.entryPoints=http
      - traefik.http.routers.http-odoo-museebolo-ch.middlewares=https-redirect@file
      - traefik.http.routers.https-odoo-museebolo-ch.tls=true
      - traefik.http.routers.https-odoo-museebolo-ch.tls.certresolver=letsencrypt
      - traefik.http.routers.https-odoo-museebolo-ch.entrypoints=https
      - traefik.http.routers.https-odoo-museebolo-ch.middlewares=bolo-auth@file
      - traefik.http.routers.https-odoo-museebolo-ch.rule=Host(`odoo.museebolo.ch`)
      - traefik.http.services.http-odoo-museebolo-ch.loadbalancer.server.port=8069
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

  db:
    image: postgres:12.2-alpine
    restart: always
    networks:
      - lan
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=Oj8Du8
      - POSTGRES_PASSWORD=koo4hah1Lus6bazo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

volumes:
  web-data:
  db-data:
  extra-addons:

networks:
  lan:
    driver: bridge
  wan:
    name: traefik_wan
    external: true


# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
